### ISSUE TITLE
Concat Whole Volume On Update

### ISSUE THREAD

**Issue by jstirling** [gvellut/jncep#10]
As a feature request I'm curious if you'd be willing to add an argument to concat all existing parts of the current volume whenever there is a new part found in the `jncep update`. Currently it only grabs the newly found parts and puts them together. I like to keep the whole volume all in 1 epub file and just replace it in calibre/on my reader so I'm forced to manually do a `jncep epub --parts [volume#]` every time there's an update, obsoleting the track system for me.

**Comment by jstirling** [comment]
Had some spare time so dug through a bit and made a quick PR https://github.com/gvellut/jncep/pull/11.

**Comment by gvellut** [comment]
Thank you for your contribution. I have merged the pull request.
