### ISSUE TITLE
No Longer Getting Parts

### ISSUE THREAD

**Issue by thargan81** [gvellut/jncep#14]
Since yesterday evening, jncep is no longer able to fully donwload new parts from the site. Any attempt to do so does generate an epub, but other than the cover the only text is this:

`You are using an old version of our app that is no longer supported. Please upgrade now to the new J-Novel Club app!`

This appears to tie in with this forum post: https://forums.j-novel.club/topic/5142/developer-psa-labs-j-novel-club-is-your-new-friend/31?page=2

This is happening with the most recent version, commit a91fcb0

**Comment by gvellut** [comment]
Actually, the current version uses the new API. I can generate an EPUB with the content. 

Can you show me : 
- the exact command you use
- the log of what you get by running with the `-d` flag? ie using `jncep -d ....`

Thank you.

**Comment by thargan81** [comment]
So, this is a classic example of why looking at issues before coffee is bad. Turns out that, for some reason, I've got two copies of jncep on the same box. One of which was updated, and one of which was in path.

**Comment by gvellut** [comment]
OK Great.
