### ISSUE TITLE
Tool no longer appending "Complete" when downloading entire volume

### ISSUE THREAD

**Issue by K-o-R** [gvellut/jncep#19]
I have tried both passing a volume URL, e.g. `jncep epub https://j-novel.club/series/hell-mode#volume-3` and also specifying a volume number e.g. `jncep epub -p 3 https://j-novel.club/series/hell-mode` but it doesn't seem to be recognising it as "complete".

**Comment by gvellut** [comment]
Thank you for your feedback.

The "Complete" info is not actually included in the API provided by J-Novel Club, so jncep fetches the j-novel.club webpage for the series, which contains a structure with the info (that the webpage uses for rendering). 

But I I just saw that structure has been changed, at least for Hell Mode. I will update the code and make a new release soon.

**Comment by K-o-R** [comment]
Wonderful, thank you for your time :)

**Comment by gvellut** [comment]
I have made a new release. It should fix the issue you had.

(as an aside, I saw that JNC has added a new attribute for determining completeness to the API directly so the code is a bit simpler)
