### ISSUE TITLE
[Feature request] Environment variable for save location

### ISSUE THREAD

**Issue by BradleyDS2** [gvellut/jncep#25]
Hi there, thanks for continuing to develop and maintain this tool, I use it around on around a weekly basis.
I have two ways I mainly use it. The first and main is by opening a command prompt window and simply entering 'jncep update', then running the resulting epub through kepubify and copying it to a prepub folder on my Kobo.
This downloads the epubs to the cwd, which is the user path since it's running in a cmd window.

Due to how often I use JNCEP, this has resulted in my C:\users\[user] directory becoming very cluttered (just did a clean-up, there were 560 epub + kepub total).
Would it be possible to specify a custom location via an environment variable? That way I could direct it to always save in a dedicated folder.

The second way I use it is quite a bit different, but would also benefit from this change.
For when I'm not at home, I have a docker container that runs a flask server that displays the following:
![image](https://user-images.githubusercontent.com/2174921/188315752-aef3b2d9-26d3-4568-80e7-724ae12ca22c.png)
Upon receiving a 'POST' with the series URL and specified part(s), it runs ```
subprocess.call(
            ["python", "-m", r"jncep.jncep", "epub", requested_url, "--parts", request.form['prepub_parts']],
            cwd=r'/app')
```
The end of create_epub has been modified to write `epub_generation_options.output_dirpath + '\n' + output_filename` to a text file, and the flask server reads this file to see where to load the epub from, loads it to a BytesIO object, sends it then deletes the epub and text file.

Very, very hacky and inelegant solution, but it works for my need, and single user (myself) when needed. Since it's just myself, I don't have to worry about any race conditions such as two users requesting a file at the same time.

If this was implemented, I'd be able to remove the need for the text file. I would instead specify an empty dedicated directory, and when the file is created it would check this directory, send the file then delete it. This would remove any need to modify jncep itself.



On an unrelated note, regarding your maybe TODO of 'self-contained executable for macOS and Windows with PyInstaller', PyInstaller is super easy to use.
To make it self contained, use the -F/--onefile flag. Check out the 'build' step here for an idea of how to integrate it with GitHub actions, so it automatically creates the executables when you make a commit with a version tag https://github.com/mc51/Clipster-Desktop-Py/blob/master/.github/workflows/build.yml

**Comment by gvellut** [comment]
Thank you for your feedback.

The `epub` and `update` commands have a `-o / --output` option to define a directory on which to write the output (default: The current directory). There is also an environment variable `JNCEP_OUTPUT` that can be set. Is it not what you want? 

For the PyInstaller thing, I tried it with another project and indeed it was quite easy to obtain the executable. But I haven't had the motivation to finish setting it up with the Github actions. But I will try to finish it soon.

**Comment by BradleyDS2** [comment]
Note to self: Don't read documentation while half asleep.


Yep, that's exactly what I was after, thank you!
