### ISSUE TITLE
Jncep update not functioning as I am expecting it to

### ISSUE THREAD

**Issue by StarLight-Oliver** [gvellut/jncep#27]
Hi there,

When I try to update preexisting volumes the update command seems to not work correctly.

An example is Apothecary Diaries
Currently has up to part 14 out.
However, even if I run the command it doesn't update past part 12, which was the latest part when I started to follow.
(the field in tracked.json)
`  "https://j-novel.club/series/the-apothecary-diaries": {
    "name": "The Apothecary Diaries",
    "part": "6.12",
    "part_date": "2022-08-26T19:00:00Z"
  },`

And the command I am running is 
`jncep update -v -s -w`

It's able to do one pull by volume. 

Not sure if this is a bug or just me doing something wrong.

**Comment by StarLight-Oliver** [comment]
That did it -s was the problem. 
looks like it only updates newly synced volumes with -s set.
I am on windows  and I am running version 37 of jncep

**Comment by gvellut** [comment]
OK great.
