### ISSUE TITLE
[Feature Request] Custom naming

### ISSUE THREAD

**Issue by mizz141** [gvellut/jncep#29]
Currently when updating a series, it jncep generates a name based on the Volume and Parts of the Prepub, I'd like a configuration where only the Volume is shown and numbered, additionally flags could be set for converting spelled out numbers into decimals and removing underscores etc.

this is doable on linux currently with 

"Rebuild_World_Volume_2_Part_Two_Parts_1_to_9.epub"

You'd get "Rebuild_World_Volume_2_Part_Two.epub"

now if the spelled out numbers could be regenerated into a decimal:

"Rebuild_World_Volume_2_Part_2.epub"

Adding some padding and replacing the "part" with a decimal:

"Rebuild_World_Volume_02.2.epub"

**Comment by gvellut** [comment]
Thank you for your feedback.

Isn't there some text missing from the post? (actual Linux commands).

At first glance, I would say, that if it is doable outside jncep, it doesn't seem necessary to add transformations in the program itself.

However, for the transformations you want, if you can list them, then I would accept a patch that would add an option that takes as values a rule name (or list of rule names) to apply to the file names.

**Comment by mizz141** [comment]
https://gist.github.com/mizz141/4ef0c984c51d3968525aaf2a2666d071

It works somehow lol

**Comment by gvellut** [comment]
OK Thanks. I will have a look.

**Comment by gvellut** [comment]
It took a while but I got around to implement that feature (it turns out it was something I needed and I wanted to take into account your use case and mine). It is a bit complex and not documented yet but I will do that for the next release.
