### ISSUE TITLE
Getting error for tracking on Windows

### ISSUE THREAD

**Issue by Zorg64** [gvellut/jncep#3]
`C:\Windows\system32>systeminfo`
`OS Name:                   Microsoft Windows 10 Pro`
`OS Version:                10.0.18363 N/A Build 18363`

`C:\Windows\system32>python --version`
`Python 3.8.5`

`C:\Windows\system32>pip --version`
`pip 20.1.1 from c:\users\user\appdata\local\programs\python\python38\lib\site-packages\pip (python 3.8)`

`C:\Windows\system32>jncep track --email user@email.com --password "somepass" https://j-novel.club/c/black-summoner-volume-1-part-1`

`Login with email 'user@email.com'...`
`Fetching metadata for 'black-summoner-volume-1-part-1'...`
`*** An unrecoverable error occured ***`
`'WindowsPath' object has no attribute 'decode'`

Alternatively running jncep epub seems to work fine.

**Comment by gvellut** [comment]
Thank you for your feedback.

I have released a new version that might fix this issue (I cannot test on Windows so I am just guessing...). Can you check ? 
To update jncep, you can do `pip install jncep --upgrade`.

If it doesn't fix the issue, can you edit line 11 in file `c:\users\user\appdata\local\programs\python\python38\lib\site-packages\jncep\jncep.py` and change it to `DEBUG = True`? Then rerun the command that fails and post the error message here. Thank you.

**Comment by Zorg64** [comment]
Seems to have fixed the issue. Thanks!
