### ISSUE TITLE
[Feature Request] Download whole volume when last part is released

### ISSUE THREAD

**Issue by pajoh** [gvellut/jncep#31]
Would it be possible to add a switch "Download whole volume on last part", that downloads both the last part like normal update, but also downloads the full volume. 

I've done a quick fix locally for me that works, but would be nice if it was added so I don't have to apply the dirty fix each time I pull from here. It's not close to be good enough for a PR though.

**Comment by gvellut** [comment]
OK it can be added.

Even if it is not ready, you can send me your changes as a PR (I will arrange it if needed).

**Comment by gvellut** [comment]
Thank you for your PR. I have edited a little bit (refactored the surrounding function essentially). I have also changed the name of the option: It is called --whole-final (to match the Final suffix used in the generated EPUBs) and the env var is called JNCEP_WHOLE_FINAL. I will test some more and make a release soon.
