### ISSUE TITLE
jncep update --sync or --jnc-managed fails

### ISSUE THREAD

**Issue by pajoh** [gvellut/jncep#35]
**Describe the bug**
Sync requires is_beginning or it'll crash

**Expected behavior**
Shouldn't crash

**To Reproduce**
jncep update -j -v -f --email <email> --password <password>

**Debug trace**
⚡ Logged in with email '<email>'
update --sync
Logout...
*** ❌ An unrecoverable error occured ***
sync_series_forward() missing 1 required positional argument: 'is_beginning'

**Environment (please complete the following information):**
 - JNCEP version: [e.g. v44]

**Comment by gvellut** [comment]
Thank you. I should have tested more... (I made a correction different from your PR: The `--beginning` is not necessary for `update --sync` => that command is like:  `track --sync` then for all new tracked series, an epub is generated  from the beginning, so the `--beginning` is implicit).
