### ISSUE TITLE
[Feature Request] Sub folders per series.

### ISSUE THREAD

**Issue by AnAngryBrit** [gvellut/jncep#39]
jncep know the series name already, as show in the `jncep track list`.

would it be possible to add an option so that when generating EPUBs they are put into a sub folder of the series that they belong to?

something like.
`jncep config set SUBFOLDER true`

then it would create and add the EPUBs to a subfolder of the name of the series.

`Success! EPUB generated in 'jncep_folder/Ascendance_of_a_Bookworm_Part_5_Volume_6_Complete.epub'!`
would look like.
`Success! EPUB generated in 'jncep_folder/Ascendance of a Bookworm/Ascendance_of_a_Bookworm_Part_5_Volume_6_Complete.epub'!`

I request this for 2 reasons:

1.  some books change the title of the books 
`Success! EPUB generated in 'jncep_folder/The_Reincarnated_Prince_and_the_Kingdom_in_Woe_Volume_1_Complete.epub'!`
`Success! EPUB generated in 'jncep_folder/The_Reincarnated_Prince_and_the_Twilight_Knight_Volume_2_Complete.epub'!`
`Success! EPUB generated in 'jncep_folder/The_Reincarnated_Prince_and_the_Haloed_Sage_Volume_3_Complete.epub'!`
`Success! EPUB generated in 'jncep_folder/The_Reincarnated_Prince_and_the_Hero_of_Light_Volume_4_Complete.epub'!`
`Success! EPUB generated in 'jncep_folder/The_Reincarnated_Prince_and_Felvolk_s_Greatest_Treasure_Volume_5_Complete.epub'!`
this makes it harder to do it outside of jncep.

2. it would make managing your books with something like Kavita an almost automatic process. 
cron jncep would downloads to sub folder
kavita library is configured on the folder of the jncep download folder and used the sub folders to catalogue the books/parts.
instant remote and managed access to your new parts.

**Comment by gvellut** [comment]
Thank you for your PR. I will have a look.

**Comment by gvellut** [comment]
Implemented in #40
