### ISSUE TITLE
passing credentials on the command line is insecure

### ISSUE THREAD

**Issue by precurejunkie** [gvellut/jncep#4]
Passing passwords on the command line is not secure, since any process on the system can read your command line while the script is running.

Environment vars (also available) are better, but may not be any more secure than the command line, depending on your OS (on some OSes other processes can read /proc/{pid}/environ)

It would be better to do one or more of the following:
1. Store it in a properly-secured config file (owner-only readable)
1. Allow it to be passed in on stdin after the process starts (i.e. cat pwfile | jncep ...)
1. Allow you to pass the name of a file that contains the password (which might possibly be '-' for stdin)

**Comment by precurejunkie** [comment]
er, I see 1 up there is implented already in the last month, I probably downloaded mine before you added that. :-)  See my caveat though, on some OSes other processes can still read that by looking at /proc/{pid}/environ

**Comment by gvellut** [comment]
Thank you for your feedback.

I understand your concern but I personally don't care enough about it to implement the change. Sorry.

If you want to work on it, I would accept a patch for your option 1 though. There is already a ~/.jncep folder created for tracking so the auth file could be under that directory. On top of the code, the documentation (the part about authentication) should also be updated.

**Comment by precurejunkie** [comment]
Yeah, I'm not particularly worried myself as I'm also the only user of the box I'm using it on... it was just kind of a "good coding practices" thing.  I might send you a PR eventually if I get some time to mess with it.
