### ISSUE TITLE
[Feature] Option for update to ONLY generate whole volumes

### ISSUE THREAD

**Issue by olee** [gvellut/jncep#43]
It would be nice to have an option for the update commend like `--whole-only` or so.th. like that to never generate partial epubs, but instead only full volumes when a final part has been released.
This would allow extending eg. a calibre library only with proper books and not all those partials.

**Comment by gvellut** [comment]
OK it could be added. 

There is already a `--whole-final` option, which does generate the final ePubs, as well as the partial ones (original issue #31). I guess there could be an option as well to prevent the generation of partial ePubs, or, as you propose, an option that does both the `--whole-final` thing AND prevents partial ePubs from being generated.

**Comment by olee** [comment]
Yeah - that's exactly the option I would be looking for 👍

**Comment by gvellut** [comment]
I have added the `--whole-only` as you proposed. It will be included in the next `jncep` release.
