### ISSUE TITLE
Can't download cover image for Banner of the Stars vol 1

### ISSUE THREAD

**Issue by justdave** [gvellut/jncep#5]
See https://forums.j-novel.club/topic/3725/403-error-on-cover-image-for-banner-of-the-stars-vol-1 including response from myskaros

Looks like the code is assuming part 1 has the title image, which isn't always guaranteed.

```json
  "https://j-novel.club/s/crest-of-the-stars": {
    "name": "Crest of the Stars",
    "part": "7.5"
  },
```

**Comment by gvellut** [comment]
Thank you for your feedback.

I have checked. From the API, the data for the first part of the volume lists some image as an attachment but when getting that image, the CDN returns Unauthorized ( https://d2dq7ifhe7bu0f.cloudfront.net/Part-5d9fab18da58e673227d761b/banner1_cvr_860.jpg ) and that is what you see according to the error message in your link. I didn't handle failure to fetch that image in the code. The similarly named image in the second part works correctly, though.

For info, the reason the cover image is fetched from the data for the first part is that, usually the first part has a bigger image listed as attachement than what is listed for the volume (which is a bit small for an e-reader). But in this case, the API returns something inexistant. 

What I will do is, if the largest image in the first part of the volume cannot be fetched, fallback to the second part... until the last ... and then finally fallback to the image in the volume. I will fix this this week-end probably.

**Comment by gvellut** [comment]
I have uploaded a new version of the tool that should fix the issue you had. Let me know if not the case. 

I have also added a few other minor changes: https://github.com/gvellut/jncep/releases/tag/v0.15

You can upgrade with: `pip install jncep --upgrade`

**Comment by justdave** [comment]
confirmed, it works!
