### ISSUE TITLE
-f param used twice

### ISSUE THREAD

**Issue by pajoh** [gvellut/jncep#55]
**Describe the bug**
Both option "is_whole_volume_on_final_part" and "is_whole_volume_only" uses "-f" as option,

When using the -f param it will use "is_whole_volume_only'"

**Comment by gvellut** [comment]
Thank your for the bug report.

I will update the param.

**Comment by gvellut** [comment]
I merged the fix in your PR: https://github.com/gvellut/jncep/pull/58
