### ISSUE TITLE
Tracking with API V2 seems off

### ISSUE THREAD

**Issue by Nitrousoxide** [gvellut/jncep#59]
**Describe the bug**
 Tracking seems to be incorrectly reporting the current status of series.

Example: Apothecary Diaries

Running a new sync for this series give the most recent update as:
  "https://j-novel.club/series/the-apothecary-diaries": {
    "last_check_date": "2024-10-11T20:46:17Z",
    "name": "The Apothecary Diaries",
    "part": "13.9",
    "part_date": "2024-12-06T20:00:00Z",
    "series_id": "SER-Y47WOHQ"

This is reporting 13.9 as the most recent entry, while only 13.2 has currently been released.  It's also reporting the part_date as December 6th, 2024 (or 2024/12/06 in decreasing time intervals), while the most recent part was released today, October 11, 2024 (aka 2024/10/11)

This seems to be leading to it skipping pulling the most recent entries because it thinks that the most recent update is in the future.

I personally had it miss grabbing this entry when I tried to have it pull the synced series earlier today and had to manually pull this 

**Expected behavior**
It should track the correct part and time.

**To Reproduce**

1. navigate to existing tracked.json file and remove it to obtain a clean slate
2. jncep track sync

**Debug trace**

[JNCEP_trace.txt](https://github.com/user-attachments/files/17347495/JNCEP_trace.txt)

**Environment (please complete the following information):**
 - OS: Alpine (installed in a podman container using this containerfile (https://github.com/Nitrousoxide/jncep/blob/master/Containerfile)
 - Python version: 3.11
 - JNCEP version: I am on version 47, based on commit e5fd32a.

**Comment by gvellut** [comment]
Thank you for the bug report.

The change last week in the J-Novel Club API added unreleased parts in the response (with a launch date field in the future). As you have noticed, it has not been handled erverywhere in the `jncep` release from yesterday so I will do that this week-end.

**Comment by jzkmath** [comment]
I see this issue was fixed but do you know when you will be publishing this release as V48?

**Comment by Nitrousoxide** [comment]
> I see this issue was fixed but do you know when you will be publishing this release as V48?

While you're waiting, you can install from the tmpfix branch of the repo, which has the fix in place.

`pip install git+https://github.com/gvellut/jncep.git@tmpfix`

is the command to do so.

**Comment by jzkmath** [comment]
Just updated to version 48. I am noticing that jncep update does not seem to work. Whenever i run this command it says everything is up to date despite at least 4 prepubs that i track have been updated.

**Comment by Nitrousoxide** [comment]
Did you purge your existing track file?  I'm not sure if it will overwrite dates in the future with new info.

I personally deleted my track file and let it rebuild it and it's worked since

**Comment by jzkmath** [comment]
> Did you purge your existing track file? I'm not sure if it will overwrite dates in the future with new info.
> 
> I personally deleted my track file and let it rebuild it and it's worked since

I just did that and I will let you know if that fixed that once a new volume comes out. Something should be available in about 2 hours for me.

**Comment by jzkmath** [comment]
Just did an update and the purging and remaking of the tracked list seems to have solve that issue.

now there is a new issue though which is that now I am unable to upload these to google play books without having to fix formatting using calibre to convert to MOBI and back to EPUB. (EPUB files with formatting errors will cause it to fail processing on google play books)

**Comment by Nitrousoxide** [comment]
I'm glad remaking the tracked list worked!  
You might want to open a new issue relating to the epub formatting since this issue is closed and it's not really related to its topic.
