### ISSUE TITLE
Concurrent volume releases

### ISSUE THREAD

**Issue by justdave** [gvellut/jncep#6]
Today, JNC released *Altina the Sword Princess* Volume 8 Part 1, and also released *Altina: Loose Threads* Part 1.  The latter is tagged as volume 9 of the main Altina series on the back end.

As you can guess, jncep downloaded parts 8.1 and 9.1, stuck them into the same epub file with each other, and marked my last-read at 9.1.

I'm pretty sure I can fix the first problem with an existing command line switch the app already has. :-)

The second one is a little harder.  I can't really think of an easy way to handle that in the app.  Although...  the final part of a volume is marked as final in some way, right? I remember seeing FINAL tagged on it when they get downloaded.  Perhaps if the last part of a volume isn't marked as final, add another line in the tracking config for that series to keep watching that volume, with a separate last read in it?  I dunno, anything I can think of sounds like it would be complicated to implement.

**Comment by gvellut** [comment]
Thank you for notifying me.

If you want to download volume 8 and 9 in different epub files, you can use the `-v` switch:

`jncep epub -s 8:9 -v https://j-novel.club/s/altina-the-sword-princess`

Unfortunately, the `update` command assumes volumes are released in sequential order.

However what you propose may be enough for a solution for this case. There is indeed some way to determine if a volume is final: There is a data field for a volume that indicates the total number of parts. However, it is not foolproof : For some volumes (older ones though, so probably doesn't matter for updates), it is not there. Also I saw for one volume that there was an additional part after the one indicated as the last one (I guess maybe the translator did not have time to finish a part in time and it got split).

Or add some way for the user to tell that a volume is its own series (for the purpose of updates) i.e let the user handle it. That might be the simplest.

In any case, I will have to think about it so maybe I will make a fix for next week.

**Comment by justdave** [comment]
Does the -v switch work with the update command?

**Comment by gvellut** [comment]
It does. However, since you have already called `update`, the part is set to 9.1 in the the file that tracks the updates and the `update` command will do nothing (or you would need to edit the file, but simpler to just call `epub`).

**Comment by justdave** [comment]
yeah, just wanted to make sure I get my wrapper script fixed for next time.

**Comment by gvellut** [comment]
I have released a new version https://github.com/gvellut/jncep/releases/tag/v0.17 that should fix the issue with Altina.

Now, the `update` command uses the publishing dates: The date of the last updated part is recorded and the next time `update` is run, if new parts have been published since, they are downloaded and the last publishing date is recorded and so on . For Altina, if you use `-v` with the `update` command, the parts for the normal series and the side stories should be in different EPUB files (but without, they are kept in the same file).

You can use `pip install --upgrade jncep` to upgrade.

Let me know if this fixes things for you.

**Comment by justdave** [comment]
New version doesn't even run.

```
*** An unrecoverable error occurred ***
dictionary changed size during iteration
```

**Comment by gvellut** [comment]
What command did you run?

**Comment by justdave** [comment]
`jncep update --email "$EMAIL" --password "$PASSWORD" -v`

**Comment by justdave** [comment]
Just to confirm, I just pulled version 0.18 and that one works again. :)

**Comment by justdave** [comment]
And I knocked my pointer for altina back to 8.1 and let it re-download 9.1 and set the date in the tracking file, will let you know how it works as soon as 8.2 and 9.2 come out.

**Comment by justdave** [comment]
Now running version 0.19. it correctly downloaded 8.2 and 9.2 and ignored 9.1. yay!

**Comment by gvellut** [comment]
OK Great!
