### ISSUE TITLE
[Feature Request] Download all available catchup series

### ISSUE THREAD

**Issue by jpazer** [gvellut/jncep#60]
Not sure if there is a good way to do it, but I would love a way to specify that I want to download all of the available catchup series, then I could run that once a month and have them all saved for later.

**Comment by gvellut** [comment]
It could be posible. Not sure if there is a way to retrieve all the catchup series (with a filter) or I you have to check all the series individually (there is a `catchup` field).

**Comment by gvellut** [comment]
I have added that (`jncep update --catchup`). It will be available in the next release.

Commit (for later reference): https://github.com/gvellut/jncep/commit/37be332155d65617f6831fc551aa09921db6a72a

**Comment by K-o-R** [comment]
This is an awesome option. Combining with `--byvolume` seems to be a good idea, unless you like (virtual) doorstoppers.
