### ISSUE TITLE
[feature request] set belongs-to-collection attribute in epub file

### ISSUE THREAD

**Issue by justdave** [gvellut/jncep#9]
There is apparently a "belongs-to-collection" attribute in the epub metadata which can be used to tell what series a book belongs to.  My e-reader (Moon+ Reader Pro) can sort on that, but the epubs generated by jncep don't have that tag set in them, so they don't show up when using the Series view.

https://www.w3.org/publishing/epub3/epub-packages.html#sec-belongs-to-collection

**Comment by gvellut** [comment]
OK I will add it.

**Comment by gvellut** [comment]
I have made a new release. Let me know if it works for your EPUB reader (I only tested in Calibre).

**Comment by justdave** [comment]
It's working, thanks!
I have my wrapper script set to auto-update jncep before running it every time, and I didn't realize it had updated.  I went into the series tab and saw bunches of series listed, and was surprised.  Came back to look at this ticket "he must had added it already" and indeed you had.  :-)

**Comment by gvellut** [comment]
OK great!
